# This TOML document describes the bug injection parameters

title = "Bug injection parameters" 

[rng]
fixed_seed = true
rng_seed = 17

[bug]
bug_type = "hang"
n_bugs = 3
injection_probability = 0.1
max_bugs_per_function = 1
max_bugs_per_basic_block = 1

